language: go
go:
- 1.5
before_install:
- go get github.com/tools/godep
script:
- godep restore
- godep go build ./...
- godep go test 
- godep go test ./storage
- godep go test ./drivers
- godep go test ./model

